### ISSUE TITLE
Could we call dart functions from luascript

### ISSUE THREAD

**Issue by winterdl** [drydart/flutter_lua#3]
Could we export dart functions then call from luascript?

**Comment by av** [comment]
Right now, it doesn't look like there's any interop between Dart code and Lua code when Lua code is running. Would be happy to be wrong on that :)

**Comment by fireton** [comment]
Without bindings it mostly useless.

**Comment by Aaron009** [comment]
I really want this feature, it can facilitate me to perform a row of operations.

**Comment by Aaron009** [comment]
@fireton @av I request network data in lua, and then refresh the UI interface. But to request network data and refresh the UI interface, need to call the dart function
